apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-breeze-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: breeze-agent
  template:
    metadata:
      labels:
        app: breeze-agent
    spec:
      containers:
        - name: breeze-agent
          image: CONTAINER_REGISTRY_HOSTNAME/breeze-agent-ds:latest
          imagePullPolicy: Always
          volumeMounts:
          - name: host-fs-opt
            mountPath: /opt
          - name: host-fs-etc
            mountPath: /etc
      volumes:
      - name: host-fs-opt
        hostPath:
          path: /opt
      - name: host-fs-etc
        hostPath:
          path: /etc
      imagePullSecrets:
      - name: IMAGE_PULL_SECRETS_NAME