apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-breeze-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: breeze-agent
  template:
    metadata:
      labels:
        app: breeze-agent
    spec:
      containers:
        - name: breeze-agent
          image: 241106941283.dkr.ecr.us-east-2.amazonaws.com/breeze-agent:ds
          imagePullPolicy: Always
          command: ["/bin/bash", "-c"]
          args: ["cp -R /{tmp,opt}/breeze-agent/ && cp /{tmp,opt}/tini && chroot /var/root /opt/tini -- /opt/breeze-agent/breeze-daemon"]
          env:
          - name: BREEZE_RUN_INTERVAL
            value: "2"
          volumeMounts:
          - name: host-fs-opt
            mountPath: /opt
          - name: host-fs-root
            mountPath: /var/root
          - name: host-mnt
            mountPath: /var/root/mnt
          # securityContext:
          #   privileged: true
      volumes:
      - name: host-fs-opt
        hostPath:
          path: /opt
      - name: host-fs-root
        hostPath:
          path: /
      - name: host-mnt
        hostPath:
          path: /mnt
      imagePullSecrets:
      - name: ecrcred